### ISSUE TITLE
What does the resulting app do ?

### ISSUE THREAD

**Issue by Gys** [tiaanduplessis/bolt-starter#15]
I cloned the repository into a new dir, did 'yarn' and then 'react-native run-ios'. It starts a simulator and opens the app. At the bottom is a button with '+ New List'. Clicking on the button does not do anything. But I assume another screen should open ?
Using latest xcode and OSX.

**Comment by Gys** [comment]
On clicking the 'New List' button the log says `Bolt[18795] <Notice>: please attach method to this component`

That makes sense, because `this.toggleInput` is not defined in https://github.com/tiaanduplessis/bolt-starter/blob/master/src/screens/TodoList.js#L61

**Comment by tiaanduplessis** [comment]
Will look into it thanks 👍

**Comment by tiaanduplessis** [comment]
Should be resolved with the latest version

**Comment by Gys** [comment]
Works perfect. Thanks for this !
