### ISSUE TITLE
Look into firebase integration

### ISSUE THREAD

**Issue by tiaanduplessis** [tiaanduplessis/bolt-starter#2]
- [firebase](https://www.npmjs.com/package/firebase)
- [react-native-firestack](https://github.com/fullstackreact/react-native-firestack)
- [react-native-fcm](https://github.com/evollu/react-native-fcm)
- [react-native-firebase-crash-report](https://github.com/ianlin/react-native-firebase-crash-report)
- [react-native-firebase-analytics](https://github.com/evollu/react-native-firebase-analytics)

**Comment by Thawab** [comment]
also 

- https://github.com/invertase/react-native-firebase
